### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by KrisBuytaert** [poolski/puppet-packetbeat#1]
While I was looking at forks of my module , I was happy to find yours and I am looking into testing it and contributing back.   

I wasn't so happy however to see that you have changed the License from GPLv2 to Apache, which is something you , according to the original license , couldn't do.

What's your take on this ?

**Comment by poolski** [comment]
Hey, 

I think that snuck in when I used the puppet module generator. 
Thanks for the heads up - I'll change that back.

**Comment by KrisBuytaert** [comment]
No worries .. figured it was something like that .. care to send back some PR's ?

**Comment by poolski** [comment]
I've merged all the PRs and published the updated module on the Forge :)
